# Generated by Django 5.1.1 on 2024-09-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренды', 'verbose_name_plural': 'Бренд'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand_name',
        ),
    ]
