# Generated by Django 5.1.1 on 2024-10-24 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_service_owner_servicerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(null=True, upload_to='cars', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Детали обслуживания'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='cars.service', verbose_name='Сервис'),
        ),
    ]
