# Generated by Django 5.1.1 on 2024-11-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_picture_alter_car_brand_alter_owner_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
