# Generated by Django 5.1.1 on 2024-11-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_service_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(null=True, upload_to='services', verbose_name='Изображение'),
        ),
    ]
